//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 原始程式碼已由 Microsoft.VSDesigner 自動產生，版本 4.0.30319.42000。
// 
#pragma warning disable 1591

namespace NTUST.BulkMail.Services.NtustMember {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://dss18.ntust.edu.tw/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback dorm_roomOperationCompleted;
        
        private System.Threading.SendOrPostCallback studnoOperationCompleted;
        
        private System.Threading.SendOrPostCallback membersOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::NTUST.BulkMail.Services.Properties.Settings.Default.NTUST_BulkMail_Services_NtustMember_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event dorm_roomCompletedEventHandler dorm_roomCompleted;
        
        /// <remarks/>
        public event studnoCompletedEventHandler studnoCompleted;
        
        /// <remarks/>
        public event membersCompletedEventHandler membersCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dss18.ntust.edu.tw/dorm_room", RequestNamespace="http://dss18.ntust.edu.tw/", ResponseNamespace="http://dss18.ntust.edu.tw/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet dorm_room(string semester, string roomno) {
            object[] results = this.Invoke("dorm_room", new object[] {
                        semester,
                        roomno});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void dorm_roomAsync(string semester, string roomno) {
            this.dorm_roomAsync(semester, roomno, null);
        }
        
        /// <remarks/>
        public void dorm_roomAsync(string semester, string roomno, object userState) {
            if ((this.dorm_roomOperationCompleted == null)) {
                this.dorm_roomOperationCompleted = new System.Threading.SendOrPostCallback(this.Ondorm_roomOperationCompleted);
            }
            this.InvokeAsync("dorm_room", new object[] {
                        semester,
                        roomno}, this.dorm_roomOperationCompleted, userState);
        }
        
        private void Ondorm_roomOperationCompleted(object arg) {
            if ((this.dorm_roomCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.dorm_roomCompleted(this, new dorm_roomCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dss18.ntust.edu.tw/studno", RequestNamespace="http://dss18.ntust.edu.tw/", ResponseNamespace="http://dss18.ntust.edu.tw/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet studno(string semester, string studentno) {
            object[] results = this.Invoke("studno", new object[] {
                        semester,
                        studentno});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void studnoAsync(string semester, string studentno) {
            this.studnoAsync(semester, studentno, null);
        }
        
        /// <remarks/>
        public void studnoAsync(string semester, string studentno, object userState) {
            if ((this.studnoOperationCompleted == null)) {
                this.studnoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnstudnoOperationCompleted);
            }
            this.InvokeAsync("studno", new object[] {
                        semester,
                        studentno}, this.studnoOperationCompleted, userState);
        }
        
        private void OnstudnoOperationCompleted(object arg) {
            if ((this.studnoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.studnoCompleted(this, new studnoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dss18.ntust.edu.tw/members", RequestNamespace="http://dss18.ntust.edu.tw/", ResponseNamespace="http://dss18.ntust.edu.tw/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet members(string id, string semester) {
            object[] results = this.Invoke("members", new object[] {
                        id,
                        semester});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void membersAsync(string id, string semester) {
            this.membersAsync(id, semester, null);
        }
        
        /// <remarks/>
        public void membersAsync(string id, string semester, object userState) {
            if ((this.membersOperationCompleted == null)) {
                this.membersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmembersOperationCompleted);
            }
            this.InvokeAsync("members", new object[] {
                        id,
                        semester}, this.membersOperationCompleted, userState);
        }
        
        private void OnmembersOperationCompleted(object arg) {
            if ((this.membersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.membersCompleted(this, new membersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void dorm_roomCompletedEventHandler(object sender, dorm_roomCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class dorm_roomCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal dorm_roomCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void studnoCompletedEventHandler(object sender, studnoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class studnoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal studnoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void membersCompletedEventHandler(object sender, membersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class membersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal membersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591