//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTUST.BulkMail.Web.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://dss18.ntust.edu.tw/", ConfigurationName="ServiceReference1.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dss18.ntust.edu.tw/dorm_room", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet dorm_room(string semester, string roomno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dss18.ntust.edu.tw/dorm_room", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> dorm_roomAsync(string semester, string roomno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dss18.ntust.edu.tw/studno", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet studno(string semester, string studentno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dss18.ntust.edu.tw/studno", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> studnoAsync(string semester, string studentno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dss18.ntust.edu.tw/members", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet members(string id, string semester);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dss18.ntust.edu.tw/members", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> membersAsync(string id, string semester);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : NTUST.BulkMail.Web.ServiceReference1.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<NTUST.BulkMail.Web.ServiceReference1.Service1Soap>, NTUST.BulkMail.Web.ServiceReference1.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet dorm_room(string semester, string roomno) {
            return base.Channel.dorm_room(semester, roomno);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> dorm_roomAsync(string semester, string roomno) {
            return base.Channel.dorm_roomAsync(semester, roomno);
        }
        
        public System.Data.DataSet studno(string semester, string studentno) {
            return base.Channel.studno(semester, studentno);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> studnoAsync(string semester, string studentno) {
            return base.Channel.studnoAsync(semester, studentno);
        }
        
        public System.Data.DataSet members(string id, string semester) {
            return base.Channel.members(id, semester);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> membersAsync(string id, string semester) {
            return base.Channel.membersAsync(id, semester);
        }
    }
}
