//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTUST.BulkMail.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumCollegePeriodDepartmentYear
    {
        public string mail { get; set; }
        public string filename { get; set; }
        public string idno { get; set; }
        public string name { get; set; }
        public string sno1 { get; set; }
        public string educode { get; set; }
        public string email { get; set; }
        public string graduateyear { get; set; }
        public string CollegeCode { get; set; }
        public string College { get; set; }
        public string PeriodCode { get; set; }
        public string Period { get; set; }
        public string DepartmentCode { get; set; }
        public string Department { get; set; }
        public string year { get; set; }
        public string foreignermark { get; set; }
        public string china_mark { get; set; }
        public string AbroadMark { get; set; }
        public string reply { get; set; }
    }
}
