//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTUST.BulkMail.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class educode
    {
        public string EduCode1 { get; set; }
        public string College1 { get; set; }
        public string Period2 { get; set; }
        public string sPeriod2 { get; set; }
        public string Department2 { get; set; }
        public string Grade1 { get; set; }
        public string Class1 { get; set; }
        public string Team2 { get; set; }
    }
}
